name: Snyk Vulnerability Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Snyk
      - name: Set up Snyk
        #uses: snyk/actions/setup@v2
        uses: snyk/actions/setup@master
        with:
          token: ${{ secrets.SNYK_TOKEN }}

      # Step 3: Run Snyk Test
      - name: Snyk Test
       # uses: snyk/actions/test@v2
        uses: snyk/actions/setup@master
        with:
        #  severity-threshold: high # This lie is used to fail the pipeline when vulnerabilities are detected
          monitor-when-failed: true

      # Step 4: Snyk Monitor # to continuously track the state of the project in the Snyk dashboard:
      - name: Snyk Monitor
        uses: snyk/actions/monitor@v3
        with:
          project-name: Nausica-s_Global_Group_2
