name: Snyk Vulnerability Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code/Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install dependencies (e.g., for a Node.js project)
      - name: Install dependencies
        run: npm install

      # Step 3: Authenticate with Snyk (Snyk API token)
      - name: Authenticate with Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      # Step 4: Run Snyk Test on the project
      - name: Run Snyk Test
        run: snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}  # Use the Snyk API token from GitHub Secrets

      # Step 5: Monitor results and upload to Snyk dashboard
      - name: Monitor Project in Snyk Dashboard
        run: snyk monitor #--file=package.json --file=yarn.lock
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
