name: SonarCloud Manual Analysis for JS/TS Projects

on:
  # Allow manual triggering
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to analyze'
        required: false
        default: 'main'

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Run tests and generate coverage (adjust command for your project)
      - name: Run tests
        run: |
          npm test -- --coverage

      # Step 5: Run SonarCloud analysis
      - name: Run SonarCloud Analysis
        env:
          GITHUB_TOKEN: ${{ secrets.NGGI_REPO_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npx sonar-scanner \
          -Dsonar.projectKey=your_project_key \
          -Dsonar.organization=your_organization_name \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
