on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          token: ${{ secrets.NGGI_REPO_TOKEN }}
         # docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
         # target: 'https://www.zaproxy.org/' ---> Need to provide the web application URL for the scan to work
         # rules_file_name: '.zap/rules.tsv'
         # cmd_options: '-a'
